apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  labels:
    role: app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      nodeSelector:
        role: app
      containers:
        - name: demoapp
          image: demoapp:latest
          imagePullPolicy: Never # use local image
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
